# Generated by Django 3.2.7 on 2021-10-04 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='car_id')),
                ('brand', models.CharField(max_length=30, verbose_name='brend')),
                ('model', models.CharField(max_length=30, verbose_name='model')),
                ('rent_cost', models.FloatField(verbose_name='cost')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('cliend_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='client id')),
                ('passport_series', models.CharField(max_length=20, verbose_name='passport seriya')),
                ('first_name', models.CharField(max_length=30, verbose_name='name')),
                ('last_name', models.CharField(max_length=30, verbose_name='surname')),
                ('phone', models.CharField(max_length=15, verbose_name='contact')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='order id')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('from_date', models.DateField(verbose_name='from date')),
                ('to_date', models.DateField(verbose_name='to date')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.cars', verbose_name='car id')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.clients', verbose_name='client id')),
            ],
        ),
        migrations.CreateModel(
            name='ExOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='ex from date')),
                ('to_date', models.DateField(verbose_name='ex to date')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.clients', verbose_name='ex client id')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.orders', verbose_name='ex order id')),
            ],
        ),
    ]
